### ISSUE TITLE
Linux test workflow fails due to tkinter

### ISSUE THREAD

**Issue by Arkh42** [Arkh42/GreatPublicationPlanner#4]
From log:
```
ImportError: Failed to import test module: test_data_processor
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/GreatPublicationPlanner/GreatPublicationPlanner/greatpublicationplanner/tests/test_data_processor.py", line 10, in <module>
    import greatpublicationplanner._data_processor as processor
  File "/home/runner/work/GreatPublicationPlanner/GreatPublicationPlanner/greatpublicationplanner/__init__.py", line 8, in <module>
    import greatpublicationplanner._file_manager as file_manager
  File "/home/runner/work/GreatPublicationPlanner/GreatPublicationPlanner/greatpublicationplanner/_file_manager.py", line 14, in <module>
    from tkinter import Tk
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by Arkh42** [comment]
Maybe due to undeclared dependency.

**Comment by Arkh42** [comment]
Interesting post here (in French): [Problème pour importer le module tkinter](https://openclassrooms.com/forum/sujet/resolu-probleme-pour-importer-le-module-tkinter).
More general post about tkinter: [ImportError: No module named 'Tkinter'](https://stackoverflow.com/questions/25905540/importerror-no-module-named-tkinter).

**Comment by Arkh42** [comment]
Still not working... Look at this post about [GitHub Action for python - import of "tkinter" fails](https://github.community/t5/GitHub-Actions/GitHub-Action-for-python-import-of-quot-tkinter-quot-fails/td-p/40644).
